package constants

const (
	BundleDocs                   string = "Docs"
	BundleDocsIntro              string = "DocsIntro"
	BundleHome                   string = "Home"
	BundleHomeIntroduction       string = "HomeIntroduction"
	BundleLogin                  string = "Login"
	BundleLogout                 string = "Logout"
	BundleProfile                string = "Profile"
	BundleSettings               string = "Settings"
	BundleAuthenticationRequired string = "AuthenticationRequired"
	BundleNavigateToLogin        string = "NavigateToLogin"
	BundlePageNotFound           string = "PageNotFound"
	BundleNavigateToHome         string = "NavigateToHome"
	BundlePageNotFoundTitle      string = "PageNotFoundTitle"
	BundleWelcome                string = "Welcome"
	BundleEmail                  string = "Email"
	BundlePassword               string = "Password"
	BundleRegister               string = "Register"
	BundleRegisterQuestion       string = "RegisterQuestion"
	BundleForgotPasswordQuestion string = "ForgotPasswordQuestion"
	BundleResetPassword          string = "ResetPassword"
	BundleInvalidEmailOrPassword string = "InvalidEmailOrPassword"
	BundleNotAuthenticatedTitle  string = "NotAuthenticatedTitle"
)
